dist: xenial
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh | bash
- curl -o p.zip https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip && unzip p.zip
- curl -o tf.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip && unzip tf.zip
- curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip
- pip install --user ansible-lint
#- sudo apt update
#- sudo apt install software-properties-common
#- sudo apt-add-repository --yes --update ppa:ansible/ansible
#- sudo apt install ansible
script:
  if: type = pull_request OR ( branch = master AND type = push )
  - ./tests/on_pull_requests.sh
#- if [ $TRAVIS_EVENT_TYPE == "pull_request" ] || ( [ $TRAVIS_EVENT_TYPE == "push" ] && [ $TRAVIS_BRANCH == "master" ] ) then ./tests/on_pull_requests.sh; fi
notifications:
  slack:
    rooms:
      secure: ObUwlJm2QU8+mIoLnyww8Haw+zxk4PBaFS1GyGH7Sv3PB3eU9mDpmhh9mGJoqd4RPhS+iHu7R7/ZUURHAElvsQkEX8pnTLsw0CtFyBgsYH1yd6QWhsxX/hJMO/BlFafkm401y7ZDFz0QB9fRmDRPtX9dczKfmqkKRkEBZz+kPdqGhH9RHGO+ZmdXFYUW3THnFT4fyhbRJ+K6hoR1WaiP/XTPbqIKqVdQUkm8qLcXL++KCZDFgc3Lrm8ECZXY0cxS09lASC9kfLYdNi/l/vyk5TNZa3KTILwlUyxGVbOyxkljoIbB6206g4lFVMJW0fXerMbzlsB12ebrLXxGEJV1QhfvklGXbS7HEJL1nPh94K9rVUT94B1QAHdcGN7L+OiwLUr/3L59dZ8nzrDwGIhi2j5fyyq+5G5CUWNH9FNowwasohh3OyBxYB+geOos9BkVHVrurlFYR2FZlz69RDZ9PqjljZbGUQQnuJc60g4OCIDG+Zvo7iV8Av6XLJUWzY/KoKKCVUEYIXf+iM7pNQcHCWKL621gzc8JS5NEhBKSSXf+1B0FDiF99yofKrMwTFuYMy0vNhyCWKwOFBN5zdG8taY7TgDAzGvW5sypwgkaS230N+ymrYTEpEW/tZyTh2sI1Dc1QbPV2juhjq+CLwFUf+oLBrj7TTCEBjnBEO3W5Sc=
