---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 10.130.0.8
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure app host
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.130.0.8
  tasks:
  - name: Add app owner
    user:
      name: appuser
      shell: /bin/bash
      create_home: true
      append: yes
  - name: Add app owner public key
    authorized_key:
      user: appuser
      key: "{{ lookup('file', '~/.ssh/appuser.pub') }}"
      manage_dir: true
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
    tags: app-tag
  - name: enable puma
    systemd: name=puma enabled=yes
    notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded

- name: Deploy app
  hosts: app
  become: true
  tags: deploy-tag
  tasks:
  - name: Install git
    apt: pkg=git state=present
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
    notify: owner set
  - name: bundler install
    bundler:
      state: present
      chdir: /home/appuser/reddit

  handlers:
  - name: owner set
    command:
      cmd: chown -R appuser:appuser ~appuser
      warn: false
#  - name: reload puma
#    become: true
#    systemd: name=puma state=restarted
