---
# tasks file for app
- name: Add app owner
  user:
    name: appuser
    shell: /bin/bash
    create_home: true
    append: yes

- name: Add app owner public key
  authorized_key:
    user: appuser
    key: "{{ lookup('file', 'appuser.pub') }}"
    manage_dir: yes
  when: not ansible_check_mode

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: Enable puma service
  systemd:
    name: puma
    enabled: yes
  notify: reload puma
