- name: Configure app host
  hosts: _tags_app
  become: true
  vars:
    db_host: 10.130.0.15
  tasks:
  - name: Add app owner
    user:
      name: appuser
      shell: /bin/bash
      create_home: true
      append: yes
  - name: Add app owner public key
    authorized_key:
      user: appuser
      key: "{{ lookup('file', 'files/appuser.pub') }}"
      manage_dir: true
    when: not ansible_check_mode
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
      owner: appuser
      group: appuser
  - systemd: name=puma enabled=yes
    notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded
