---
- name: Deploy app
  hosts: app
  become: true
  tasks:
  - name: Install git
    apt: pkg=git state=present
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
    when: not ansible_check_mode
  - name: bundler install
    bundler:
      state: present
      chdir: /home/appuser/reddit
  - name: Set app owner
    command:
      cmd: chown -R appuser:appuser ~appuser
      warn: false
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
